# Generated by Django 4.1.5 on 2023-01-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dash", "0002_products_productcategory_alter_products_productimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="productcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Goods", "Goods"),
                    ("Electronics", "Electronics"),
                    ("Foods", "Foods"),
                    ("Bags", "Bags"),
                ],
                max_length=15,
            ),
        ),
    ]
